-- CAU 3.1. Tạo ra 3 users: GIANGVIEN, GIAOVU và SINHVIEN, đặt mật khẩu tuỳ ý. 

-- Chay trong master
USE master;
GO
CREATE LOGIN GIAOVIEN WITH PASSWORD = 'GV@123456';
CREATE LOGIN GIAOVU   WITH PASSWORD = 'GVu@123456';
CREATE LOGIN SINHVIEN WITH PASSWORD = 'SV@123456';
GO

-- Chay trong database cua bai tap
USE QLDT;
GO
CREATE USER GIANGVIEN FOR LOGIN GIAOVIEN;
CREATE USER GIAOVU   FOR LOGIN GIAOVU;
CREATE USER SINHVIEN FOR LOGIN SINHVIEN;
GO

-- CAU 3.2. PHAN QUYEN
-- GIAOVU: xem va cap nhat tat ca cac bang

DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'GRANT SELECT, UPDATE ON OBJECT::'
    + QUOTENAME(SCHEMA_NAME(schema_id)) + N'.' + QUOTENAME(name)
    + N' TO GIAOVU;' + CHAR(13)
FROM sys.tables;
EXEC sys.sp_executesql @sql;
GO


-- GIANGVIEN: xem thong tin giang vien, de tai va hoi dong

GRANT SELECT ON dbo.GIAOVIEN TO GIANGVIEN;
GRANT SELECT ON dbo.GV_HDT TO GIANGVIEN;
GRANT SELECT ON dbo.GV_PHDT TO GIANGVIEN;
GRANT SELECT ON dbo.GV_UVDT TO GIANGVIEN;
GRANT SELECT ON dbo.DETAI TO GIANGVIEN;
GRANT SELECT ON dbo.HOIDONG TO GIANGVIEN;
GRANT SELECT ON dbo.HOIDONG_GV TO GIANGVIEN;
GRANT SELECT ON dbo.HOIDONG_DT TO GIANGVIEN;
GRANT SELECT ON dbo.HOCVI TO GIANGVIEN;
GRANT SELECT ON dbo.HOCHAM TO GIANGVIEN;
GRANT SELECT ON dbo.CHUYENNGANH TO GIANGVIEN;
GRANT SELECT ON dbo.GV_HV_CN TO GIANGVIEN;
GO

-- Neu giang vien can xem ten sinh vien gan voi de tai, cap them quyen tren hai bang lien quan:

GRANT SELECT ON dbo.SINHVIEN TO GIANGVIEN;
GRANT SELECT ON dbo.SV_DETAI TO GIANGVIEN;
GO

-- GIANGVIEN: chi cap nhat thong tin cua minh
-- Tao bang lien ket tai khoan database voi ma giang vien
CREATE TABLE dbo.TAIKHOAN_GV
(
    TenUser SYSNAME NOT NULL PRIMARY KEY,
    MaGV CHAR(5) NOT NULL UNIQUE,
    CONSTRAINT FK_TAIKHOAN_GV_GIAOVIEN
        FOREIGN KEY (MaGV) REFERENCES dbo.GIAOVIEN(MaGV)
);
GO

-- View chi hien thi mot so truong thong tin ca nhan duoc phep cap nhat
CREATE VIEW dbo.vw_ThongTinGiangVienCuaToi
AS
    SELECT GV.MaGV, GV.TenGV, GV.DiaChi, GV.SDT, GV.NamSinh
    FROM dbo.GIAOVIEN AS GV
    WHERE GV.MaGV =
        (SELECT TK.MaGV
         FROM dbo.TAIKHOAN_GV AS TK
         WHERE TK.TenUser = USER_NAME())
WITH CHECK OPTION;
GO

GRANT SELECT, UPDATE ON dbo.vw_ThongTinGiangVienCuaToi TO GIANGVIEN;
GO


-- SINHVIEN: xem thong tin sinh vien, hoi dong va de tai
GRANT SELECT ON dbo.SINHVIEN TO SINHVIEN;
GRANT SELECT ON dbo.HOIDONG TO SINHVIEN;
GRANT SELECT ON dbo.DETAI TO SINHVIEN;
GO




-- Cam xoa du lieu cho ca ba user
DENY DELETE TO GIANGVIEN;
DENY DELETE TO GIAOVU;
DENY DELETE TO SINHVIEN;
GO