-- CAU 3.1. Tạo ra 3 users: GIANGVIEN, GIAOVU và SINHVIEN, đặt mật khẩu tuỳ ý. 

-- Chay trong master
USE master;
GO
CREATE LOGIN GIAOVIEN WITH PASSWORD = 'GV@123456';
CREATE LOGIN GIAOVU   WITH PASSWORD = 'GVu@123456';
CREATE LOGIN SINHVIEN WITH PASSWORD = 'SV@123456';
GO

-- Chay trong database cua bai tap
USE QLDeTai;
GO
CREATE USER GIAOVIEN FOR LOGIN GIAOVIEN;
CREATE USER GIAOVU   FOR LOGIN GIAOVU;
CREATE USER SINHVIEN FOR LOGIN SINHVIEN;
GO

-- CAU 3.2. PHAN QUYEN
-- GIAOVU: xem va cap nhat tat ca cac bang

USE QLDeTai;
GO
DECLARE @sql NVARCHAR(MAX) = N'';
SELECT @sql += N'GRANT SELECT, UPDATE ON OBJECT::'
    + QUOTENAME(SCHEMA_NAME(schema_id)) + N'.' + QUOTENAME(name)
    + N' TO GIAOVU;' + CHAR(13)
FROM sys.tables;
EXEC sys.sp_executesql @sql;
GO


-- GIANGVIEN: xem thong tin giang vien, de tai va hoi dong

GRANT SELECT ON dbo.GIANGVIEN TO GIAOVIEN;
GRANT SELECT ON dbo.GV_HDT TO GIAOVIEN;
GRANT SELECT ON dbo.GV_PHDT TO GIAOVIEN;
GRANT SELECT ON dbo.GV_UVDT TO GIAOVIEN;
GRANT SELECT ON dbo.DETAI TO GIAOVIEN;
GRANT SELECT ON dbo.HOIDONG TO GIAOVIEN;
GRANT SELECT ON dbo.HOIDONG_GV TO GIAOVIEN;
GRANT SELECT ON dbo.HOIDONG_DT TO GIAOVIEN;
GRANT SELECT ON dbo.HOCVI TO GIAOVIEN;
GRANT SELECT ON dbo.HOCHAM TO GIAOVIEN;
GRANT SELECT ON dbo.CHUYENNGANH TO GIAOVIEN;
GRANT SELECT ON dbo.GV_HV_CN TO GIAOVIEN;
GO

-- Neu giao vien can xem ten sinh vien gan voi de tai, cap them quyen tren hai bang lien quan:

GRANT SELECT ON dbo.SINHVIEN TO GIAOVIEN;
GRANT SELECT ON dbo.SV_DETAI TO GIAOVIEN;
GO

-- GIANGVIEN: chi cap nhat thong tin cua minh
-- Tao bang lien ket tai khoan database voi ma giang vien
CREATE TABLE dbo.TAIKHOAN_GV
(
    TenUser SYSNAME NOT NULL PRIMARY KEY,
    MaGV CHAR(5) NOT NULL UNIQUE,
    CONSTRAINT FK_TAIKHOAN_GV_GIANGVIEN
        FOREIGN KEY (MaGV) REFERENCES dbo.GIANGVIEN(MaGV)
);
GO

-- View chi hien thi mot so truong thong tin ca nhan duoc phep cap nhat
CREATE VIEW dbo.vw_ThongTinGiangVienCuaToi
AS
    SELECT GV.MaGV, GV.TenGV, GV.DiaChi, GV.SDT, GV.NamSinh
    FROM dbo.GIANGVIEN AS GV
    WHERE GV.MaGV =
        (SELECT TK.MaGV
         FROM dbo.TAIKHOAN_GV AS TK
         WHERE TK.TenUser = USER_NAME())
WITH CHECK OPTION;
GO

GRANT SELECT, UPDATE ON dbo.vw_ThongTinGiangVienCuaToi TO GIAOVIEN;
GO


-- SINHVIEN: xem thong tin sinh vien, hoi dong va de tai
GRANT SELECT ON dbo.SINHVIEN TO SINHVIEN;
GRANT SELECT ON dbo.HOIDONG TO SINHVIEN;
GRANT SELECT ON dbo.DETAI TO SINHVIEN;
GO




-- Cam xoa du lieu cho ca ba user
DENY DELETE TO GIAOVIEN;
DENY DELETE TO GIAOVU;
DENY DELETE TO SINHVIEN;
GO